baseURL = "https://everythingisgray.com/"
footnoteReturnLinkContents = "↩"
languageCode = "en-us"
theme = "ananke"
title = "Everything is Gray"

[params]
  AuthorName = "James Barclay"
  GitHubUser = "futureimperfect"
  SidebarRecentLimit = 5
  Subtitle = "A place to put stuff."

[permalinks]
  post = "/:year/:month/:day/:title/"
