# Deploy site to GitHub Pages on commit to master branch.
name: github-pages-deploy

on:
  # Triggers the workflow on push events but only to the master branch.
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-24.04
    env:
      HUGO_VERSION: 0.140.1
    steps:
      - name: Setup Hugo
        # TODO: Update to use peaceiris/actions-hugo once `withDeploy` is supported.
        #
        # https://github.com/peaceiris/actions-hugo/issues/658
        # uses: peaceiris/actions-hugo@v3
        # with:
        #   hugo-version: '0.140.1'
        #   extended: true
        run: |
          sudo apt-get install -y build-essential
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Install Dart Sass
        run: sudo snap install dart-sass

      # Checks-out the repository under $GITHUB_WORKSPACE,
      # so the job can access it.
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Build
        env:
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
          HUGO_ENVIRONMENT: production
        run: make build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          cname: everythingisgray.com
          commit_message: ${{ github.event.head_commit.message }}
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: futureimperfect/futureimperfect.github.io
          # Allows you to make your publish branch only
          # include the latest commit.
          force_orphan: true
          publish_branch: master
          publish_dir: ./public
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
